const questions = [
    "What is your favorite color?",
    "What is your favorite food?",
    "Do you have any pets?",
    "What is a fun fact about you?",
    "If you could visit any place in the world, where would it be?",
    "What's your favorite hobby?",
    "What kind of music do you enjoy?",
    "Do you prefer coffee or tea?",
    "What's a movie you could watch over and over again?",
    "Do you play any video games? If so, which ones?",
    "What's the best book you've ever read?",
    "What's one thing on your bucket list?",
    "What is your dream job?",
    "What's your favorite way to spend a weekend?",
    "If you could have any superpower, what would it be?",
    "What is your favorite holiday?",
    "What TV show are you currently watching?",
    "What was your first ever gaming console?",
    "If you could have dinner with any famous person, dead or alive, who would it be?",
    "What’s your favorite thing to do in your free time?",
    "Are you more of a morning person or a night owl?",
    "Do you like pineapple on pizza?",
    "What’s a skill you’ve always wanted to learn?",
    "If you could instantly master one language, which would it be?",
    "What’s the weirdest food you’ve ever tried?",
    "Do you like cats or dogs more?",
    "What was your favorite childhood cartoon?",
    "What's the last song you listened to?",
    "If you had unlimited money for a day, what would you do?",
    "Do you prefer summer or winter?",
    "What's one thing you’re really good at?",
    "What’s your favorite ice cream flavor?",
    "Do you have any favorite YouTubers or streamers?",
    "What's a hobby you recently picked up?",
    "If you had to eat one meal for the rest of your life, what would it be?",
    "What’s your dream vacation destination?",
    "What’s your favorite thing about gaming?",
    "Have you ever met someone famous?",
    "What’s one thing you wish you could tell your younger self?",
    "Do you prefer texting or calling?",
    "If you had a time machine, would you visit the past or the future?",
    "What’s the best advice you’ve ever received?",
    "What’s your go-to comfort food?",
    "Do you have any hidden talents?",
    "What's your favorite type of dessert?",
    "Would you rather explore space or the deep ocean?",
    "What’s your favorite board game or card game?",
    "If you could swap lives with any fictional character for a day, who would it be?",
];

module.exports = questions;
